### ISSUE TITLE
KeyError: 'at'

### ISSUE THREAD

**Issue by pcpong** [devnicolasc/SonoffBasic#4]
>> sonoff = Sonoff(username='XXX', password='XXX')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tp_pf01.POWERSYNC\Anaconda3\lib\site-packages\SonoffBasic\sonoff.py", line 23, in __init__
    self.login()
  File "C:\Users\tp_pf01.POWERSYNC\Anaconda3\lib\site-packages\SonoffBasic\sonoff.py", line 42, in login
    self.token = r['at']

**Comment by tom8635** [comment]
is there any update to this, I have the same error, stopped working overnight, no updates or restarts
